CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98
NAMENAMENAME
NAMENAMENAME
NAMENAMENAME
SURNAME = a.out
SRCS = main.cpp
OBJS = $(SRCS:.cpp=.o)

all: $(SURNAME)
$(SURNAME): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@
clean:
	rm -f $(OBJS)
fclean: clean
	rm -f $(SURNAME)
re: fclean all
.PHONY: all clean fclean re
